### ISSUE TITLE
Missing polyfill

### ISSUE THREAD

**Issue by palrogg** [IMI-initiative/quatre-apparts-et-un-confinement#160]
We write es8 code but we didn’t do anything to polyfill yet.
Currently:
* doesn’t work on iPhone 4 and 5 (blank page)
* SnowHaze: some glitches, stops working at bus scene
* …
(We need more real device testing btw)

**Comment by Dobios** [comment]
> We write es8 code but we didn’t do anything to polyfill yet.
> Currently:
> 
>     * doesn’t work on iPhone 4 and 5 (blank page)
> 
>     * SnowHaze: some glitches, stops working at bus scene
> 
>     * …
>       (We need more real device testing btw)

Do you think that simply using [core-js](https://github.com/zloirock/core-js) should be enough to fix that?

**Comment by palrogg** [comment]
`babel-preset-env` may be used with core-js: https://babeljs.io/docs/en/6.26.3/babel-preset-env
There may be other ways to add core-js to the webpack bundling process. And we could improve the config.
Feel free to give it a try, I’m not a polyfill expert!

**Comment by palrogg** [comment]
More about the babel config: https://babeljs.io/docs/en/usage
About the preset config: https://babeljs.io/docs/en/babel-preset-env
And a good post explaining what happens under the hood: https://blog.jakoblind.no/babel-preset-env/
