### ISSUE TITLE
Sprite and music optimization

### ISSUE THREAD

**Issue by palrogg** [IMI-initiative/quatre-apparts-et-un-confinement#164]
Our game download size is 100 MB. Some files need optimization (**examples** below). We should also remove ~~unused sprites~~.

`WARNING in asset size limit: The following asset(s) exceed the recommended size limit (879 KiB).
This can impact web performance. Assets:`

-   bundle.min.js (1.4 MiB)
-   sounds/building/theme.mp3 (899 KiB)
-   sounds/building/sadTheme.mp3 (899 KiB)
-   sounds/supermarket/cashier.wav (884 KiB)
-   sounds/grandma/bleibenJazz.mp3 (1.16 MiB)
-   **sounds/supermarket/Supermarket.mp3 (1.99 MiB)**
-   sprites/ProtoScene/WakeUpCard/bg.jpg (905 KiB)
-   **sounds/ZoomMiniGame/ZoomGame2.mp3 (2.61 MiB)**
-   sprites/BusScene/Bus01/Bus01-01-bus.png (1.46 MiB)
-   **sounds/ZoomMiniGame/ZoomGame1.mp3 (2.67 MiB)**
-   sprites/BusScene/Bus02/Bus02-01-bus.png (1.46 MiB)
-   **sounds/ZoomMiniGame/ZoomGame3.mp3 (2.5 MiB)**
-   sprites/HallwayScenes/Palier-Grand-Mere-Ouvert/bg.jpg (1.11 MiB)
-   sprites/IndepScene/02_Messages/bg.png (1.28 MiB)
-   **sounds/ZoomMiniGame/ZoomMusic.mp3 (2.9 MiB)**
-   sprites/MotherScene/02-Salon/mere-salon01_01-decor.jpg (1.03 MiB)
-   sprites/ProtoScene/ClothesCard/bg.jpg (1.17 MiB)
-   **sprites/ProtoScene/ComputerCard/bg.jpg (1.37 MiB)**
-   sprites/ProtoScene/MessageCard/bg.png (1.31 MiB)
-   **sprites/StoreExteriorScene/bg.jpg (1.1 MiB)**
-   ~~sprites/UI/Messages/08_00-modele-conversation.jpg (1.2 MiB)~~

**Comment by astonedf** [comment]
@palrogg J'ai réexporté les gros mp3 mais si on veut qu'ils fassent moins que 879Kib, ils perdent énormément en qualité. J'ai fait quelques tests d'export, la qualité est "acceptable" vers les 900Kib-1Mib, est-ce que ça suffirait ou bien?

**Comment by palrogg** [comment]
Oui, c'est excellent, merci bien! Tu utilises quel taux de compression, 128 kbps?
