### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by palrogg** [IMI-initiative/quatre-apparts-et-un-confinement#208]
* Ajouter la RTS (extraits sonores) + les différents logos dans les crédits
* Remercier tous les testeurs (compléter)

**Comment by yrochat** [comment]
I've added one name from the form. We should all ask our family and friends who've tested the game if they want to appear.

**Comment by yrochat** [comment]
I've added "Gaël" and "Mounir".

**Comment by palrogg** [comment]
G&M still missing – wip
