### ISSUE TITLE
Suggestions for translation system

### ISSUE THREAD

**Issue by palrogg** [IMI-initiative/quatre-apparts-et-un-confinement#238]
Great job, thanks a lot!

The first run works fine, but once a game was saved, it seems a DialogueController gets created before the player instantiation (which means before the language is set): `Uncaught Error: Cannot find module './undefined/damienDialogMarch.json'`

Two suggestions: 
- We could use a [“Translation Needed” issue](https://github.com/IMI-initiative/quatre-apparts-et-un-confinement/issues/237) with file names
- Maybe we could set constants for default language, page <title>, description, meta description etc.? Or we could document which lines to change (e.g. player.js line 58 `this.language = LANGUAGES.FR`)

**Comment by Dobios** [comment]
Ah darn, I didn't test that case, I'll try to set the default language to something in the case where it comes back undefined
