### ISSUE TITLE
As a player, I would like to have an end screen.

### ISSUE THREAD

**Issue by yrochat** [IMI-initiative/quatre-apparts-et-un-confinement#38]

**Comment by yrochat** [comment]
Devra comprendre (au moins) :
- nos noms à nous cinq : il va falloir se choisir des rôles
- les noms des partenaires (IMI, Le Temps, Collège des humanités EPFL, UNIL Gamelab)
- les logos correspondant ?
- une adresse email de contact ?
- autres suggestions ?

La dernière vignette de l'histoire n'est pas optimiste, avec le virus qui ne veut pas partir (un cas de Covid à la crèche) : je propose d'avoir une touche un peu légère sur le end screen, par exemple d'y insérer le gif du chat. Quel est votre avis, @astonedf ?

**Comment by astonedf** [comment]
@yrochat Oui aucun soucis! Je pense qu'un appel avec sa fille qui organise une journée avec les petits-enfants est plus optimiste et marque la fin de la solitude (fin du confinement/début de déconfinement)
