### ISSUE TITLE
The game is lacking in decent documentation.

### ISSUE THREAD

**Issue by Dobios** [IMI-initiative/quatre-apparts-et-un-confinement#55]
Maybe it's time to add a wiki entry for the documentation. Isn't urgent and can probably wait until we've finished the project.

- [x] Explain dialogs
- [x] Database information
- [x] localStorage usage
- [x] How to use continuous deploy
- [ ] JSON for messages have a different structure

**Comment by palrogg** [comment]
I’d suggest an extensive README, what do you think? Typical Wiki problem: people don’t open the tab, developers forget to keep it up to date

**Comment by palrogg** [comment]
Some infos we could add:
* SQlite database structure
* localStorage usage
* continuous deploy on Heroku

**Comment by palrogg** [comment]
Also update package.json (repo, …)

**Comment by palrogg** [comment]
Quick readme rewrite done.
